GET http://localhost:5273/games

###
GET http://localhost:5273/games/1

###
POST http://localhost:5273/games
Content-Type: application/json

{
  "name": "Minecraft",
  "genre": "Kidss and Family",
  "price": 19.99,
  "releaseDate": "2011-11-18"
}

###
PUT http://localhost:5273/games/6
Content-Type: application/json

{
    "name": "Street Figther II FULL",
    "genre": "FFighting",
    "price": 39.99,
    "releaseDate": "2000-07-15"
}

###
DELETE http://localhost:5273/games/1