GET http://localhost:5273/games

###
GET http://localhost:5273/games/9

###
POST http://localhost:5273/games
Content-Type: application/json

{
  "name": "Minecraft III",
  "genreId": "1",
  "price": 29.99,
  "releaseDate": "2011-11-18"
}

###
PUT http://localhost:5273/games/9
Content-Type: application/json

{
    "name": "Street Figther II FULL",
    "genreId": 1,
    "price": 39.99,
    "releaseDate": "2000-07-15"
}

###
DELETE http://localhost:5273/games/11


